source :rubygems
gem "rails", "~> 3.2"
gem "uglifier", ">= 1.0.3"
gem "airbrake"
gem "kaminari"
gem "mysql2"
gem "nokogiri"
gem "dynamic_form"
gem "newrelic_rpm"
gem "sanitize"
gem "execjs"
gem 'therubyracer'
gem "tidy_ffi"
gem "rack-superfeedr"
gem "annotate"
gem "bcrypt-ruby"
require "open-uri"
require "uri"
require "digest/md5"
require "digest/sha1"
require "json"
