source :rubygems
gem "rails", "3.2.1"
gem "uglifier", ">= 1.0.3"
gem "airbrake"
gem "will_paginate"
gem "mysql2"
gem "nokogiri"
gem "dynamic_form"
gem "newrelic_rpm"
gem "sanitize"
require "open-uri"
require "uri"
require "digest/md5"
